### ISSUE TITLE
About the code formatting 

### ISSUE THREAD

**Issue by Tiru-99** [software-lab-JHS/weatherApplication#5]
While editing your code please make sure to use proper formatting techniques, and there are some bugs in the login.html page , the team members are kindly requested to fix this issue

**Comment by ShravaniBhuwan** [comment]
Okay will take a look at it

**Comment by Akashpurohit77** [comment]
The bugs will be fixed soon , another advice from my side is to not use tailwind css in the production code

**Comment by jagritirsharma** [comment]
Understood, will address formatting & bugs ASAP.

**Comment by 123harshitaagrawal** [comment]
Got it, will handle the formatting and bugs promptly

**Comment by sarahkulsum** [comment]
Is the issue resolved??
